PWA + offline
go-shiori/shiori pull request #325
Opened 2022-01-30 21:29 UTC by geekgonecrazy

2022-02-06 01:09 UTC, symgryph commented
Looks like we are back in business. You might want to take a look again. New maintainer!

2022-02-18 05:18 UTC, geekgonecrazy commented
Ah fantastic!  Hopefully things pick back up.  So far just this change has made it very useful to.  Just pin to Home Screen on mobile and can read even with no internet connection :)

2022-02-18 18:27 UTC, fmartingr requested changes
Hey @geekgonecrazy, thanks for the PR! This seems amazing. I'm not currently using Shori on my mobile/tablet but this will make it very useful when traveling around.

I'm not very proficent in the front-side of things, so my not-very-expert eyes say it's almost good to go. The only thing I didn't like quite much is that we are serving static assets from the service and also fetching them from the outside. It would be good if we serve those all ourselves.

I know there's a lot of room to improve here, but we need to take it one step at a time.

CC: @m-bers as the original contributor for the PWA

2022-02-18 18:27 UTC, fmartingr commented on internal/view/index.html
> +		import 'https://cdn.jsdelivr.net/npm/@pwabuilder/pwaupdate';
Can we have this living with our other static assets? It seems weird to me that we serve everything bundled withing the binary but this is fetched from an outside service.

2022-02-18 18:27 UTC, fmartingr commented on internal/view/pwabuilder-sw.js
> +importScripts('https://storage.googleapis.com/workbox-cdn/releases/5.1.2/workbox-sw.js');
Same as before, can we bundle this within shiori?

2022-02-18 18:27 UTC, fmartingr commented on internal/webserver/server.go
> +	router.GET(jp("/pwabuilder-sw.js"), hdl.serveFile)
This should be served from `/js/...` as with the other javascript files.

2022-02-23 02:50 UTC, m-bers commented
I am just seeing this now--@geekgonecrazy evidently knows more about PWA caching than I do, but I will try to work on the web share target component which was my original aim (offline was just a bonus) and submit that as a separate PR

2022-05-12 00:32 UTC, karlprieb commented
Hey @geekgonecrazy 👋 are you still working on this PR? If not I can take a look and make the updates suggested by @fmartingr

2022-05-20 21:12 UTC, geekgonecrazy commented
@karlprieb hey my friend! :) I haven't had time to mess with this for a while.  I'll add you as contributor on my fork if you want to make more changes.

2022-10-07 09:24 UTC, fmartingr commented
Hey @geekgonecrazy, @karlprieb, is this something you are still interested on working on?

2022-10-27 16:55 UTC, karlprieb commented
Hey @fmartingr I’m still interested in working on this feature, sadly I’m not having the necessary time to do so :(

2022-10-28 06:38 UTC, fmartingr commented
Hey @karlprieb, no problem, I will just keep this open then. We all have our things in life :)

2023-04-27 14:10 UTC, ilkersigirci commented
Any updates about the progress? I think this feature is a game changer for the project.

2023-05-22 06:06 UTC, wolfhechel commented
I started working on PWA separate from this pull request and have a working PWA profile and share target but not offline caching. I would be open to reworking my patches with this PR and finish this feature.

2023-05-24 05:48 UTC, geekgonecrazy commented
> I started working on PWA separate from this pull request and have a working PWA profile and share target but not offline caching. I would be open to reworking my patches with this PR and finish this feature.

Please feel free to take what is done here and wrap into own PR 🙏

2023-07-04 08:23 UTC, pythoninthegrass commented
No ETA, but I have an [MVP working](https://github.com/go-shiori/shiori/compare/master...pythoninthegrass:shiori:shiori-mobile) locally in the iOS simulator. Up to the [publishing bit](https://docs.pwabuilder.com/#/builder/app-store?id=publishing) now.

<img src="https://github.com/go-shiori/shiori/assets/4097471/95d6b53b-231b-4f32-b10c-7848ee60bacd" width="300">

<img src="https://github.com/go-shiori/shiori/assets/4097471/2d318d55-4d27-4b3a-96b9-37c2010448d4" width="300">

<img src="https://github.com/go-shiori/shiori/assets/4097471/b97d86a7-f9a1-4b69-93e5-4ebac0819fc8" width="300">

<img src="https://github.com/go-shiori/shiori/assets/4097471/55c52728-7e5f-4c0c-b533-0fbba01beee1" width=300>

2023-07-04 10:21 UTC, fmartingr commented
> No ETA, but I have an [MVP working](https://github.com/go-shiori/shiori/compare/master...pythoninthegrass:shiori:shiori-mobile) locally in the iOS simulator. Up to the [publishing bit](https://docs.pwabuilder.com/#/builder/app-store?id=publishing) now.

Could it also be used directly from the browser by adding it to home screen/applications without the need of installing an app from the store?

2023-07-04 16:06 UTC, pythoninthegrass commented
Good point! Looks like the offline bit will need more testing.

PWA portion works pretty well, but the viewport needs adjusting for newer phones without a home button.

I'll keep at it 🤙
________________________________
From: Felipe Martin ***@***.***>
Sent: Tuesday, July 4, 2023 5:22:10 AM
To: go-shiori/shiori ***@***.***>
Cc: pythoninthegrass ***@***.***>; Manual ***@***.***>
Subject: Re: [go-shiori/shiori] PWA + offline (PR #325)


No ETA, but I have an MVP working<https://github.com/go-shiori/shiori/compare/master...pythoninthegrass:shiori:shiori-mobile> locally in the iOS simulator. Up to the publishing bit<https://docs.pwabuilder.com/#/builder/app-store?id=publishing> now.

Could it also be used directly from the browser by adding it to home screen/applications without the need of installing an app from the store?

—
Reply to this email directly, view it on GitHub<https://github.com/go-shiori/shiori/pull/325#issuecomment-1619973775>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AA7ILP3WON3RSV77TBSSPJLXOPVFFANCNFSM5NEX5UHQ>.
You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

2023-09-09 04:01 UTC, jt-wang commented
@fmartingr @pythoninthegrass Hi there, thanks for all the contribution and discussion! PWA would bring Shiori to next level to fully replace other bookmark managers (especially the default bookmark managers from Chrome and Safari). May I know if this PR is still active? If so, any context of the current blocker preventing it from being merged? Thanks.

2023-09-09 07:17 UTC, fmartingr commented
> @fmartingr @pythoninthegrass Hi there, thanks for all the contribution and discussion! PWA would bring Shiori to next level to fully replace other bookmark managers (especially the default bookmark managers from Chrome and Safari). May I know if this PR is still active? If so, any context of the current blocker preventing it from being merged? Thanks.

I can't say myself, there are some people interested in moving this forward but sadly since we do this in our free time I guess is difficult to just sit down and go on with it. I also think this would be a game changer but I'm not that into frontend development (if I were, I would refactor all of it 😂 )

2023-09-09 14:34 UTC, pythoninthegrass commented
@fmartingr hit the nail on the head. I made some progress but with the latest API changes, it became too much of a lift.

I'm pretty green at go and frontend isn't my strong suit. My fork is still available and the manifest.json (manifest.webmanifest) is about 2/3 complete according to [pwabuilder](https://www.pwabuilder.com/).

Ended up migrating to Omnivore and while it doesn't quite check all the boxes, it suits my needs and has very responsive devs who are actively implementing features I'm interested in.

2023-09-10 07:21 UTC, fmartingr commented
> @fmartingr hit the nail on the head. I made some progress but with the latest API changes, it became too much of a lift.
> 
> I'm pretty green at go and frontend isn't my strong suit. My fork is still available and the manifest.json (manifest.webmanifest) is about 2/3 complete according to [pwabuilder](https://www.pwabuilder.com/).
> 
> Ended up migrating to Omnivore and while it doesn't quite check all the boxes, it suits my needs and has very responsive devs who are actively implementing features I'm interested in.

That's sad to hear, but understandable :)

I may hop on to the task then, while I make the changes to the API. Thanks for putting your time into it anyway, really appreciated.

2023-09-10 10:49 UTC, pythoninthegrass commented
You're welcome! It was a good learning experience and appreciate what you've done to make a viable pocket alternative ☺️
________________________________
From: Felipe Martin ***@***.***>
Sent: Sunday, September 10, 2023 2:21:41 AM
To: go-shiori/shiori ***@***.***>
Cc: pythoninthegrass ***@***.***>; Mention ***@***.***>
Subject: Re: [go-shiori/shiori] PWA + offline (PR #325)


@fmartingr<https://github.com/fmartingr> hit the nail on the head. I made some progress but with the latest API changes, it became too much of a lift.

I'm pretty green at go and frontend isn't my strong suit. My fork is still available and the manifest.json (manifest.webmanifest) is about 2/3 complete according to pwabuilder<https://www.pwabuilder.com/>.

Ended up migrating to Omnivore and while it doesn't quite check all the boxes, it suits my needs and has very responsive devs who are actively implementing features I'm interested in.

That's sad to hear, but understandable :)

I may hop on to the task then, while I make the changes to the API. Thanks for putting your time into it anyway, really appreciated.

—
Reply to this email directly, view it on GitHub<https://github.com/go-shiori/shiori/pull/325#issuecomment-1712737618>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AA7ILP5VFYRAFI7PYCBZ5BDXZVTALANCNFSM5NEX5UHQ>.
You are receiving this because you were mentioned.Message ID: ***@***.***>

2024-05-10 18:03 UTC, fmartingr commented
> Any helper needed ? I wanted to make a simple pwa of shiori just to be able to share links to it, but apparently some work was done here ? I can checkout this branch and try to fix

Absolutely! The frontend side needs a hand, but if you could bring the PWA to an usable state it would be awesome tbh :)

2024-05-21 20:43 UTC, ragekit commented
Maybe a very dumb question but what is the user/pwd of the dev local dev instance ? I can't find it in the doc

2024-05-22 20:35 UTC, ragekit commented
Lots have changed since the previous devs attempt to add a PWA. I'm trying to from scratch just to add a manifest and I'm a bit confused by the routing system, fonrtend.go seems to says that the assets folder is statically accesible but alas my manifest get 404

2024-05-22 20:44 UTC, fmartingr commented
> Lots have changed since the previous devs attempt to add a PWA. I'm trying to from scratch just to add a manifest and I'm a bit confused by the routing system, fonrtend.go seems to says that the assets folder is statically accesible but alas my manifest get 404

Yeah, files stored under `internal/view/assets` are served over at `/assets/...`. You may need to restart the server for the static file system to handle those.

If you can, submit your PR in draft mode and we can provide assistance in there.

2024-05-22 20:55 UTC, ragekit commented
Allright, posted here : https://github.com/go-shiori/shiori/pull/919

2024-11-08 01:15 UTC, closed without merging