sqlite: remove unneeded LEFT JOIN to improve performance
go-shiori/shiori pull request #387
Opened 2022-02-26 00:18 UTC by tungel

I came across this project a few days ago on HackerNews and I like it very much. After using it a bit more during the last few days, I notice that the performance degrades quickly. With 1187 bookmarks (40 pages), running the shiori server (using sqlite db) on MacBook Pro (16-inch, 2019) 2.6 GHz 6-Core Intel Core i7 took around 10 seconds to load and similar amount of time to switch between pages.

I managed to track down the culprit - it's the `LEFT JOIN` statements in the `GetBookmarks` and `GetBookmarksCount` methods in the `sqlite.go` that cause the slowness.

I'm not very familiar with the code base yet but it looks like we don't need `LEFT JOIN` in those methods. Removing it helps improving performance dramatically.

Before:

```
INFO[0000] Serve shiori in :8050 /
WARN[0005] GET /api/bookmarks?keyword=&tags=&exclude=&page=1  proto=HTTP/1.1 remote="127.0.0.1:54846" reqlen=0 size=25 status=500
INFO[0007] GET /login?dst=http%3A%2F%2Flocalhost%3A8050%2F%23home  proto=HTTP/1.1 remote="127.0.0.1:54846" reqlen=0 size=4376 status=200
INFO[0010] POST /api/login                               proto=HTTP/1.1 remote="127.0.0.1:54846" reqlen=61 size=101 status=200
INFO[0010] GET /                                         proto=HTTP/1.1 remote="127.0.0.1:54846" reqlen=0 size=5659 status=200
2022/02/26 10:43:21 Start GetBookmarksCount...
2022/02/26 10:43:32 End GetBookmarksCount
2022/02/26 10:43:32 Start GetBookmarks...
2022/02/26 10:43:32 End GetBookmarks
INFO[0021] GET /api/bookmarks?keyword=&tags=&exclude=&page=1  proto=HTTP/1.1 remote="127.0.0.1:54846" reqlen=0 size=10997 status=200
INFO[0021] GET /api/tags                                 proto=HTTP/1.1 remote="127.0.0.1:54846" reqlen=0 size=4206 status=200
2022/02/26 10:43:52 Start GetBookmarksCount...
2022/02/26 10:44:02 End GetBookmarksCount
2022/02/26 10:44:02 Start GetBookmarks...
2022/02/26 10:44:02 End GetBookmarks
INFO[0051] GET /api/bookmarks?keyword=&tags=&exclude=&page=1  proto=HTTP/1.1 remote="127.0.0.1:55174" reqlen=0 size=10997 status=200
INFO[0051] GET /api/tags                                 proto=HTTP/1.1 remote="127.0.0.1:55174" reqlen=0 size=4206 status=200
2022/02/26 10:44:18 Start GetBookmarksCount...
2022/02/26 10:44:29 End GetBookmarksCount
2022/02/26 10:44:29 Start GetBookmarks...
2022/02/26 10:44:30 End GetBookmarks
INFO[0079] GET /api/bookmarks?keyword=&tags=&exclude=&page=2  proto=HTTP/1.1 remote="127.0.0.1:55419" reqlen=0 size=9959 status=200
2022/02/26 10:44:42 Start GetBookmarksCount...
2022/02/26 10:44:52 End GetBookmarksCount
2022/02/26 10:44:52 Start GetBookmarks...
2022/02/26 10:44:53 End GetBookmarks
INFO[0102] GET /api/bookmarks?keyword=&tags=&exclude=&page=3  proto=HTTP/1.1 remote="127.0.0.1:55629" reqlen=0 size=10289 status=200
```

After

```
INFO[0000] Serve shiori in :8050 /
WARN[0008] GET /                                         proto=HTTP/1.1 remote="127.0.0.1:56649" reqlen=0 size=49 status=301
INFO[0008] GET /login?dst=%2F                            proto=HTTP/1.1 remote="127.0.0.1:56649" reqlen=0 size=4376 status=200
INFO[0008] GET /css/fonts/source-sans-pro-v13-latin-200.woff2  proto=HTTP/1.1 remote="127.0.0.1:56649" reqlen=0 size=15824 status=200
INFO[0017] POST /api/login                               proto=HTTP/1.1 remote="127.0.0.1:56733" reqlen=61 size=101 status=200
INFO[0017] GET /                                         proto=HTTP/1.1 remote="127.0.0.1:56733" reqlen=0 size=5659 status=200
2022/02/26 10:46:47 Start GetBookmarksCount...
2022/02/26 10:46:47 End GetBookmarksCount
2022/02/26 10:46:47 Start GetBookmarks...
2022/02/26 10:46:47 End GetBookmarks
INFO[0017] GET /api/bookmarks?keyword=&tags=&exclude=&page=1  proto=HTTP/1.1 remote="127.0.0.1:56733" reqlen=0 size=10997 status=200
INFO[0017] GET /api/tags                                 proto=HTTP/1.1 remote="127.0.0.1:56733" reqlen=0 size=4206 status=200
2022/02/26 10:46:52 Start GetBookmarksCount...
2022/02/26 10:46:52 End GetBookmarksCount
2022/02/26 10:46:52 Start GetBookmarks...
2022/02/26 10:46:52 End GetBookmarks
INFO[0023] GET /api/bookmarks?keyword=&tags=&exclude=&page=1  proto=HTTP/1.1 remote="127.0.0.1:56733" reqlen=0 size=10997 status=200
INFO[0023] GET /api/tags                                 proto=HTTP/1.1 remote="127.0.0.1:56733" reqlen=0 size=4206 status=200
2022/02/26 10:47:02 Start GetBookmarksCount...
2022/02/26 10:47:02 End GetBookmarksCount
2022/02/26 10:47:02 Start GetBookmarks...
2022/02/26 10:47:02 End GetBookmarks
INFO[0033] GET /api/bookmarks?keyword=&tags=&exclude=&page=2  proto=HTTP/1.1 remote="127.0.0.1:56733" reqlen=0 size=9959 status=200
2022/02/26 10:47:09 Start GetBookmarksCount...
2022/02/26 10:47:09 End GetBookmarksCount
2022/02/26 10:47:09 Start GetBookmarks...
2022/02/26 10:47:09 End GetBookmarks
INFO[0039] GET /api/bookmarks?keyword=&tags=&exclude=&page=3  proto=HTTP/1.1 remote="127.0.0.1:56733" reqlen=0 size=10289 status=200
```

2022-02-26 11:11 UTC, fmartingr requested changes
Hey @tungel, thanks a lot for this catch! I agree that performance is suboptimal in extreme cases and more improvements need to be made!

That said, you can remove the join (at least not like that) in the `GetBookmarks` method because in some cases you need to retrieve the bookmarks along with it's content (for example, in exports). That's why the check is there. The problem is, though, the `bc.content` column is added and the `LEFT JOIN` performed regardless of the `opts.WithContent`. 

The `GetBookmarksCount` method is easier to check though, since the `LEFT JOIN` is done but the data from it is not used elsewhere in the query, and in the cases that is needed the data is obtained with additional queries.

So, I'd say let's remove the logs and `LEFT JOIN` from the count method and leave the `GetBookmarks` as it is for now since from your logs, it seems that the main culprit from the request delays are the `COUNT`s anyway (are always are in SQL :grimacing: )

Again, thanks for your contribution! Much appreciated.

2022-02-27 01:23 UTC, tungel commented
Thanks @fmartingr  for the feedback. I just pushed a new revision, hopefully it looks better. Please let me know what you think. Thanks.

2022-02-27 23:28 UTC, tungel commented
I just noticed that the code update in `GetBookmarks` changes the app behavior a bit: clicking on the bookmark brings the browser to the archive page instead of the readable page.

Do we want to accept this change as a tradeoff? Personally I think the performance is more important. Taking 10s+ to query a db with just 1k+ records is pretty bad imho.

(btw, from my testing, removing the join clause in `GetBookmarksCount` while keeping it in `GetBookmarks` still result in 10s query times).

If you disagree, I can remove the changes in `GetBookmarks` and we can look into a better fix later. One idea I have is to use [external content](https://www.sqlite.org/fts5.html#external_content_and_contentless_tables) to improve the performance. But this will either need to wait until we have a proper db migration mechanism or we can write a one off migration program similar to [sqlite-fts4-fts5](https://github.com/go-shiori/shiori-utils/tree/main/cmd/migration/sqlite-fts4-fts5).

2022-03-01 09:51 UTC, Rigobertomarro approved these changes
Gracias

2022-03-01 10:12 UTC, Rigobertomarro commented on internal/database/sqlite.go
>  	if opts.WithContent {
- [ ] ~~```


```~~

2022-03-01 13:07 UTC, fmartingr commented
I've been checking this a bit today, and indeed, without the `hasContent` field the frontend assumes that the bookmark has no content/archive and it directly links to the main URL. Also the icon that shows that there's readable content extracted never show up:  ![2022-03-01_13-02-13](https://user-images.githubusercontent.com/812088/156173811-fa2ab5dc-db2f-43d7-b50b-5983fb342ebc.png)

Regarding the URL, I believe we can address it easily by always redirecting to the `/bookmark/:boorkmark_id/content` path and let the backend handler check if the URL has content/archive and either show up the content, redirect to the archive or to the main bookmark URL, in that order of priority. This should work easily with pretty minor changes.

But I still see a problem with the icon above. That's an indicator that I do not want to lose, and in another project this could be easily addresable by storing two booleans on the database rather than using a join or a file path to check for existence, but since we still don't have a proper way of handing database migrations a simple `ALTER` is very cumbersome to do at the moment.

2022-03-06 09:30 UTC, tungel commented
You are right. Since there is no straight forward way to modify database at the moment, I'm willing to revert the change in `GetBookmarksCount` for this PR. Please let me know what you think.

I think the proper way to fix this issue is to have the `content` column in the `bookmark` table and use it as the external content table for FTS.

2022-03-06 20:49 UTC, fmartingr commented
> You are right. Since there is no straight forward way to modify database at the moment, I'm willing to revert the change in `GetBookmarksCount` for this PR. Please let me know what you think.
> 
> I think the proper way to fix this issue is to have the `content` column in the `bookmark` table and use it as the external content table for FTS.

That seems the proper way forward. I will start with the SQLite migrations (#392) once I have some spare time (I wanted to do something this weekend, but I'm currently traveling and don't have as much time as I thought).

2022-03-07 10:49 UTC, tungel commented
Cool. I just updated the PR to remove the changes in `GetBookmarks`.

2022-03-10 22:32 UTC, fmartingr approved these changes
Thanks for your work @tungel ! I expect to start working on the migrations this weekend. With some luck I can have a working PR. Sadly I don't have much spare time recently.

2022-03-10 22:32 UTC, merged